version: "2"
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - contextcheck
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - funlen
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - godot
    - gosec
    - gosmopolitan
    - govet
    - ireturn
    - lll
    - mnd
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - nolintlint
    - noctx
    - perfsprint
    - prealloc
    - promlinter
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - wrapcheck
    - whitespace

  settings:
    gosec:
      includes:
        - G102
        - G106
        - G108
        - G109
        - G111
        - G112
        - G201
        - G203
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - ireturn
        path: _test\.go
      - linters:
          - structcheck
          - unused
        text: '`data` is unused'
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - revive
        text: 'var-naming:'
      - linters:
          - revive
        text: 'exported:'
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - revive
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - gin.go
